version: '3.4'

services:
  # db:
  #   image: postgres
  #   #    restart: always
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_DB: postgres
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: ./frontend
      target: development
    ports:
      - '9000:9000' # Map container port to the PORT environment variable
    volumes:
      - ./frontend/src:/app/src
  backend:
    build:
      context: ./backend
      target: development
    env_file:
      - ./backend/.env
    #environment:
    #EXTERNAL_DB_URL: 'postgres://postgres:1234@db:5432/postgres'
    ports:
      - '8000:8000' # Map container port to the PORT environment variable
    volumes:
      - ./backend/src:/app/src
volumes:
  postgres_data:
